import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const rootDir = path.resolve(__dirname, '..');
const buildDir = path.join(rootDir, 'twESP32GPS', 'data');
const outputHeader = path.join(rootDir, 'twESP32GPS', 'dashboard.h');

function main() {
  console.log('=== Inlining assets and generating dashboard.h ===');

  const htmlPath = path.join(buildDir, 'index.html');
  const jsPath = path.join(buildDir, 'assets', 'index.js');
  const cssPath = path.join(buildDir, 'assets', 'index.css');

  if (!fs.existsSync(htmlPath)) {
    console.error(`[Error] HTML file not found: ${htmlPath}`);
    process.exit(1);
  }

  let htmlContent = fs.readFileSync(htmlPath, 'utf8');
  let jsContent = '';
  let cssContent = '';

  if (fs.existsSync(jsPath)) {
    jsContent = fs.readFileSync(jsPath, 'utf8');
    console.log(`- Loaded JS: ${jsPath} (${jsContent.length} bytes)`);
  } else {
    console.warn(`[Warning] JS file not found: ${jsPath}`);
  }

  if (fs.existsSync(cssPath)) {
    cssContent = fs.readFileSync(cssPath, 'utf8');
    console.log(`- Loaded CSS: ${cssPath} (${cssContent.length} bytes)`);
  } else {
    console.warn(`[Warning] CSS file not found: ${cssPath}`);
  }

  // Replace CSS link with inline style
  const cssRegex = /<link\s+rel=["']stylesheet["']\s+crossorigin\s+href=["']\/assets\/index\.css["']\s*\/?>|<link\s+rel=["']stylesheet["']\s+href=["']\/assets\/index\.css["']\s*\/?>/gi;
  if (cssRegex.test(htmlContent)) {
    htmlContent = htmlContent.replace(cssRegex, `<style>${cssContent}</style>`);
    console.log('- Inlined CSS successfully');
  } else {
    // Fallback if regex didn't match exactly
    htmlContent = htmlContent.replace('</head>', `<style>${cssContent}</style></head>`);
    console.log('- Appended CSS to </head> (fallback)');
  }

  // Remove original JS script tag from <head> and append JS content to the end of <body>
  const jsRegex = /<script\s+type=["']module["']\s+crossorigin\s+src=["']\/assets\/index\.js["']><\/script>|<script\s+type=["']module["']\s+src=["']\/assets\/index\.js["']><\/script>/gi;
  if (jsRegex.test(htmlContent)) {
    htmlContent = htmlContent.replace(jsRegex, ''); // Remove it from <head>
  }
  
  if (htmlContent.includes('</body>')) {
    htmlContent = htmlContent.replace('</body>', `<script>${jsContent}</script></body>`);
    console.log('- Inlined JS at the end of <body> successfully');
  } else {
    htmlContent += `<script>${jsContent}</script>`;
    console.log('- Appended JS to the end of HTML (fallback)');
  }

  // Generate C++ Raw String Literal header
  const headerContent = `#pragma once
#include <pgmspace.h>

// Automatically generated from Svelte frontend build.
// Do not edit this file manually.

const char DASHBOARD_HTML[] PROGMEM = R"rawhtml(
${htmlContent}
)rawhtml";
`;

  fs.writeFileSync(outputHeader, headerContent, 'utf8');
  console.log(`- Generated header file: ${outputHeader} (${headerContent.length} bytes)`);
  console.log('=== Finished generating dashboard.h ===');
}

main();
